In [1]:
##做函式

In [6]:
import pandas as pd



In [ ]:
card_df=pd.read_excel(r'./reg_card_feature_for_reccommend_1st.xlsx',encoding='utf-16',index_col=0)

In [ ]:


#函數找卡名
def recommendations():
    
    #輸入偏好
    a,b,c,d,e,f,g,h,i,j,k=0,0,0,0,0,0,0,0,0,0,0
    a=input('卡活動');b=input('保險');c=input('加油');d=input('行動支付');e=input('超商');
    f=input('交通');g=input('電影');h=input('旅遊機票飯店');i=input('網購');j=input('繳稅繳費');k=input('現金回饋');
    
    list01=[a,b,c,d,e,f,g,h,i,j,k]
    for n,i in enumerate(list01):
        if i =='':
            list01[n]=0
        else:
            list01[n]=int(i)

    #偏好正規化        
    INP=pd.DataFrame(columns=['卡活動','保險','加油','行動支付','超商','交通','電影','旅遊機票飯店','網購','繳稅繳費','現金回饋'])
    list02=[]
    for i in list01:
        l02=i/sum(list01)
        list02.append(l02)
    
    
    INP.loc[0]=list02
    #計算相似度
    x=cosine_similarity(card_df, INP)
    # print(x)
    a=list(x)
    b=sorted(a,reverse=True)
    blist=b[0:5]
    blist
    c=[]
    for i in blist:
        d=a.index(i)
        c.append(d)
    #print(c)
    return list(card_df.index[c])
    


## test 

In [1]:
def inputs(lll):
    INP=pd.DataFrame(columns=['卡活動','保險','加油','行動支付','超商','交通','電影','旅遊機票飯店','網購','繳稅繳費','現金回饋'])
    list02=[]
    for i in list01:
        l02=i/sum(lll)
        list02.append(l02)
    
    print(list02)
    
    
    INP.loc[0]=list02
    
    
#     INP.loc[n]=r'%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d'%(a,b,c,d,e,f,g,h,i,j,k)
    return(INP)

In [2]:
def numbers_i():
    a,b,c,d,e,f,g,h,i,j,k=0,0,0,0,0,0,0,0,0,0,0
    a=input('卡活動');b=input('保險');c=input('加油');d=input('行動支付');e=input('超商');
    f=input('交通');g=input('電影');h=input('旅遊機票飯店');i=input('網購');j=input('繳稅繳費');k=input('現金回饋');
    
    list01=[a,b,c,d,e,f,g,h,i,j,k]
    for n,i in enumerate(list01):
        if i =='':
            list01[n]=0
        else:
            list01[n]=int(i)
    print(list01)
    return(list01)

In [4]:
numbers_i()

卡活動1
保險2
加油2
行動支付5
超商4
交通2
電影3
旅遊機票飯店4
網購4
繳稅繳費1
現金回饋5
[1, 2, 2, 5, 4, 2, 3, 4, 4, 1, 5]


[1, 2, 2, 5, 4, 2, 3, 4, 4, 1, 5]

In [7]:

list01=numbers_i()
INP=inputs(list01)
print(INP)
    

卡活動1
保險2
加油2
行動支付5
超商4
交通2
電影3
旅遊機票飯店4
網購4
繳稅繳費1
現金回饋5
[1, 2, 2, 5, 4, 2, 3, 4, 4, 1, 5]
[0.030303030303030304, 0.06060606060606061, 0.06060606060606061, 0.15151515151515152, 0.12121212121212122, 0.06060606060606061, 0.09090909090909091, 0.12121212121212122, 0.12121212121212122, 0.030303030303030304, 0.15151515151515152]
        卡活動        保險        加油      行動支付        超商        交通        電影  \
0  0.030303  0.060606  0.060606  0.151515  0.121212  0.060606  0.090909   

     旅遊機票飯店        網購      繳稅繳費      現金回饋  
0  0.121212  0.121212  0.030303  0.151515  


In [112]:
INP
INP

卡活動      保險     加油  行動支付      超商      交通   電影  旅遊機票飯店     網購  繳稅繳費    現金回饋
0  0.0  0.0625  0.125   0.0  0.3125  0.0625  0.0    0.25  0.125   0.0  0.0625

In [9]:

import pandas as pd
import json
import re
import pymongo
import jieba
import operator
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [135]:
card_df

卡活動        保險        加油      行動支付        超商  \
三信銀行-VISA白金卡             0.192982  0.087719  0.105263  0.000000  0.052632   
上海商銀-TeresaCard          0.130573  0.076433  0.101911  0.076433  0.095541   
上海商銀-小小兵Bello回饋卡         0.139021  0.058452  0.053712  0.080569  0.069510   
上海商銀-簡單卡                 0.116412  0.057252  0.048664  0.086832  0.050573   
土地銀行-JCB一卡通聯名晶緻卡         0.125000  0.125000  0.062500  0.125000  0.125000   
土地銀行-白金商務卡               0.000000  0.000000  0.000000  0.000000  0.000000   
土地銀行-國際信用卡               0.043103  0.017241  0.017241  0.198276  0.077586   
中國信託-ANA晶緻聯名卡            0.000000  0.000000  0.000000  0.000000  0.000000   
中國信託-ANA極緻聯名卡            0.000000  0.000000  0.000000  0.000000  0.000000   
中國信託-Global Mall 聯名卡     0.000000  0.000000  0.000000  0.000000  0.000000   
中國信託-iPlan卡              0.050000  0.100000  0.000000  0.000000  0.000000   
中國信託-LEXUS聯名卡            0.000000  0.000000  0.000000  0.000000  0.000000   
中國信託-LINE Pay卡           0.092648  0.056677  0.067029  0.112125  0.077382   
中國信託-MUJI無印良品聯名卡         0.075000  0.105000  0.090000  0.120000  0.105000   
中國信託-TAIPEI 101 夜光聯名卡    0.000000  0.000000  0.000000  0.000000  0.000000   
中國信託-Yahoo聯名卡            0.123431  0.094142  0.081590  0.102510  0.066946   
中國信託-大中華攜手飛聯名卡           0.146552  0.017241  0.060345  0.094828  0.086207   
中國信託-大葉高島屋百貨聯名卡          0.333333  0.000000  0.000000  0.000000  0.000000   
中國信託-中油VIP聯名卡            0.000000  0.000000  0.000000  0.000000  0.000000   
中國信託-中信兄弟聯名卡             0.182927  0.000000  0.085366  0.030488  0.024390   
中國信託-中信商旅鈦金卡             0.095070  0.059859  0.028169  0.133803  0.116197   
中國信託-中國信託寰遊美國運通卡AMEX_金卡  0.000000  0.000000  0.000000  0.000000  0.000000   
中國信託-中華電信聯名白金卡           0.000000  0.000000  0.000000  0.000000  0.000000   
中國信託-秀泰聯名卡               0.123077  0.033846  0.083077  0.076923  0.040000   
中國信託-享想生活卡               0.048387  0.000000  0.096774  0.000000  0.080645   
中國信託-南紡購物中心聯名卡           0.116071  0.089286  0.125000  0.098214  0.098214   
中國信託-紅利御璽卡               0.085106  0.042553  0.127660  0.000000  0.085106   
中國信託-現金回饋鈦金卡             0.120603  0.025126  0.115578  0.020101  0.000000   
中國信託-勤美天地聯名晶緻卡           0.333333  0.000000  0.000000  0.000000  0.000000   
中國信託-鼎極卡                 0.077707  0.059873  0.033121  0.042038  0.045860   
...                           ...       ...       ...       ...       ...   
臺灣企銀-北港朝天宮媽祖認同卡          0.000000  0.000000  0.000000  0.000000  0.000000   
臺灣企銀-故宮之友認同卡             0.111111  0.111111  0.111111  0.000000  0.000000   
臺灣企銀-悠遊聯名卡               0.114921  0.059162  0.085079  0.095288  0.084555   
臺灣企銀-鈦金商旅卡               0.038462  0.096154  0.096154  0.096154  0.096154   
臺灣銀行-金采白金卡               0.000000  0.000000  0.000000  0.000000  0.000000   
臺灣銀行-金鑽商旅白金卡             0.000000  0.000000  0.000000  0.000000  0.000000   
臺灣銀行-鈦金商旅卡               0.131749  0.072354  0.102592  0.089633  0.073434   
遠東商銀-Bankee信用卡           0.208333  0.016667  0.000000  0.100000  0.016667   
遠東商銀-C'est Moi我的卡        0.000000  0.000000  0.000000  0.000000  0.000000   
遠東商銀-eTag 聯名卡            0.000000  0.000000  0.000000  0.000000  0.000000   
遠東商銀-New Century MC卡     0.000000  0.000000  0.000000  0.000000  0.000000   
遠東商銀-快樂信用卡               0.135654  0.091236  0.082833  0.096038  0.097239   
遠東商銀-華信航空聯名卡             0.000000  0.000000  0.000000  0.000000  0.000000   
聯邦銀行-F1 加油卡              0.000000  0.000000  0.000000  0.000000  0.000000   
聯邦銀行-Tiger City悠遊白金卡     0.000000  0.000000  0.000000  0.000000  0.000000   
聯邦銀行-大立無限卡               0.324324  0.000000  0.000000  0.000000  0.000000   
聯邦銀行-全國加油聯名卡             0.125793  0.075053  0.141649  0.114165  0.078224   
聯邦銀行-幸福御守御璽卡             0.263158  0.052632  0.000000  0.052632  0.000000   
聯邦銀行-紅利卡                 0.000000  0.000000  0.000000  0.000000  0.000000   
聯邦銀行-美華泰聯名卡              0.666667  0.000000  0.000000  0.000000  0.000000   
聯邦銀行-泰航聯名卡               0

In [11]:
x=cosine_similarity(card_df, INP)
# print(x)
a=list(x)
b=sorted(a,reverse=True)
blist=b[0:5]
blist
c=[]
for i in blist:
    d=a.index(i)
    c.append(d)
print(c)


[196, 13, 121, 122, 74]


[array([0.95793881]),
 array([0.95606212]),
 array([0.95526913]),
 array([0.95491571]),
 array([0.95190056]),
 array([0.95108753]),
 array([0.94975621]),
 array([0.94149222]),
 array([0.9403061]),
 array([0.93677854]),
 array([0.93658603]),
 array([0.93646096]),
 array([0.93607013]),
 array([0.93481056]),
 array([0.93462152]),
 array([0.93371692]),
 array([0.93103549]),
 array([0.92887562]),
 array([0.92876076]),
 array([0.9285771]),
 array([0.92731981]),
 array([0.9253339]),
 array([0.92523775]),
 array([0.92505565]),
 array([0.92323196]),
 array([0.92291965]),
 array([0.92150852]),
 array([0.92143023]),
 array([0.91996059]),
 array([0.91993532]),
 array([0.91931015]),
 array([0.91732845]),
 array([0.91697269]),
 array([0.91643928]),
 array([0.91605024]),
 array([0.91597817]),
 array([0.91583797]),
 array([0.91471508]),
 array([0.91357287]),
 array([0.91150647]),
 array([0.9102418]),
 array([0.91003869]),
 array([0.90984564]),
 array([0.90909091]),
 array([0.90904611]),
 array([0.9085

In [36]:
#recommended_card = []
# pd.Series(card_df.index)==['上海商銀-簡單卡'].index[0]
#recommended_card.append(list(card_df.index)[1])
list(card_df.index[c])

['國泰世華-KOKO COMBO icash聯名卡',
 '中國信託-MUJI無印良品聯名卡',
 '玉山銀行-Pi 拍錢包信用卡',
 '玉山銀行-U Bear信用卡',
 '台北富邦-數位生活卡']

In [21]:

#函數找卡名
indices = pd.Series(card_df.index)
def recommendations(name, cosine_sim = x):
    
    recommended_card = []
    cos_number=[]
    
    # gettin the index of the movie that matches the title
    idx = indices[indices == name].index[0]

    # creating a Series with the similarity scores in descending order
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)

    # getting the indexes of the 10 most similar movies
    top_10_indexes = list(score_series.iloc[1:11].index)
    #number=cosine_simz[idx]
    
    # populating the list with the titles of the best 10 matching movies
    for i in top_10_indexes:
        recommended_card.append(list(card_df.index)[i])
        cos_number.append(cosine_sim[idx][i])
        
    return recommended_card ,cos_number

In [22]:
recommendations('國泰世華-KOKO COMBO icash聯名卡')

([], [])

In [62]:
a=[0,1,2,3,5,4]
for n,i in enumerate(a):
    if a[n]==5:
        print(n)

4


In [ ]:
#整合

#使用者輸入偏好
def numbers_i():
    a,b,c,d,e,f,g,h,i,j,k=0,0,0,0,0,0,0,0,0,0,0
    a=input('卡活動');b=input('保險');c=input('加油');d=input('行動支付');e=input('超商');
    f=input('交通');g=input('電影');h=input('旅遊機票飯店');i=input('網購');j=input('繳稅繳費');k=input('現金回饋');
    
    list01=[a,b,c,d,e,f,g,h,i,j,k]
    for n,i in enumerate(list01):
        if i =='':
            list01[n]=0
        else:
            list01[n]=int(i)
    print(list01)
    return(list01)




In [ ]:
#使用者偏好陣列正規化
def inputs(lll):
    a,b,c,d,e,f,g,h,i,j,k=0,0,0,0,0,0,0,0,0,0,0
    a=input('卡活動');b=input('保險');c=input('加油');d=input('行動支付');e=input('超商');
    f=input('交通');g=input('電影');h=input('旅遊機票飯店');i=input('網購');j=input('繳稅繳費');k=input('現金回饋');
    
    list01=[a,b,c,d,e,f,g,h,i,j,k]
    for n,i in enumerate(list01):
        if i =='':
            list01[n]=0
        else:
            list01[n]=int(i)


    INP=pd.DataFrame(columns=['卡活動','保險','加油','行動支付','超商','交通','電影','旅遊機票飯店','網購','繳稅繳費','現金回饋'])
    list02=[]
    for i in list01:
        l02=i/sum(lll)
        list02.append(l02)
    
    print(list02)
    
    
    INP.loc[0]=list02
    
    
#     INP.loc[n]=r'%d,%d,%d,%d,%d,%d,%d,%d,%d,%d,%d'%(a,b,c,d,e,f,g,h,i,j,k)
    return(INP)


#卡片位置






In [ ]:
x=cosine_similarity(card_df, INP)
indices = pd.Series(card_df.index)

In [45]:
recommendations()

卡活動1
保險2
加油3
行動支付5
超商4
交通3
電影4
旅遊機票飯店5
網購4
繳稅繳費2
現金回饋5


['中國信託-MUJI無印良品聯名卡',
 '臺灣企銀-鈦金商旅卡',
 '玉山銀行-U Bear信用卡',
 '中國信託-LINE Pay卡',
 '臺灣企銀-悠遊聯名卡']

In [33]:
    # print(x)
    a=list(x)
    b=sorted(a,reverse=True)
    blist=b[0:5].index

    
    
    
    # gettin the index of the movie that matches the title
    idx = indices[indices == name].index[0]

    # creating a Series with the similarity scores in descending order
    score_series = pd.Series(cosine_sim[idx]).sort_values(ascending = False)

    # getting the indexes of the 10 most similar movies
    top_10_indexes = list(score_series.iloc[1:11].index)
    #number=cosine_simz[idx]
    
    # populating the list with the titles of the best 10 matching movies
    for i in top_10_indexes:
        recommended_card.append(list(card_df.index)[i])
        cos_number.append(cosine_sim[idx][i])
        
    return recommended_card ,cos_number

AttributeError: 'list' object has no attribute 'iloc'